name: CI/CD with Cortex

on:
  push:
    branches:
      - main

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install deps
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t demo-cicd-app:latest .

      # 6. Install Cortex CLI (FIXED)
      - name: Install Cortex CLI
        run: |
          curl -L https://install.cortex.io -o cortex-install.sh
          chmod +x cortex-install.sh
          ./cortex-install.sh
          echo "$HOME/.cortex/bin" >> $GITHUB_PATH

      # 7. Verify installation (DEBUG step)
      - name: Verify Cortex CLI
        run: cortex --version

      # 8. Login using secret
      - name: Cortex Login
        run: cortex login --api-key d3r1fsJinwU4va3ydeixVGnuB328dlDgr5w11NHJbT936qsu56qU4kF9Zboa6MRRVI9qGeFQXbss10LPI0DnHP5ehZQyV3f7JikD933FdeI7vi6WIBzlmegopjbXqHnA

      # 9. Scan image
      - name: Scan Docker image with Cortex
        run: cortex scan image demo-cicd-app:latest